InfoBookproject/InfoBookapp/urls.py
from django.urls import path

from . import views
from .views import BookList, BookCreate, BookInsert

app_name = 'teamapp'
urlpatterns = [
    path('', BookList.as_view(), name='index'),
    path('list/', BookList.as_view(), name='list'),
    path('create/', BookCreate.as_view(), name='create'),
    path('insert/', BookInsert.as_view(), name='insert'),
]

InfoBookproject/InfoBookproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('InfoBookapp.urls', namespace='InfoBookapp')),
]

InfoBookproject/InfoBookapp/models.py
from django.db import models
from django.db.models.fields import CharField, DateField, IntegerField, TextField

class BookInfo(models.Model):
    title = CharField(help_text='書籍名', max_length=30)
    author = CharField(help_text='著者名', max_length=30)
    yomigana = CharField(help_text='読み仮名', max_length=30)
    company = CharField(help_text='出版社', max_length=30)
    date = DateField(help_text='出版日')
    page = IntegerField(help_text='ページ数')
    chance = CharField(help_text='購入のきっかけ', max_length=100)
    overview = TextField(help_text='概要')

    def __str__(self):
        return self.title

InfoBookproject/InfoBookapp/views.py
from django.shortcuts import render
from .models import BookInfo
from django.views.generic import ListView, DetailView, CreateView

class BookIndex(ListView):
    template_name = 'index.html'
    model = BookInfo

class BookList(ListView):
    template_name = 'list.html'
    model = BookInfo

class BookCreate(CreateView):
    template_name = 'create.html'
    model = BookInfo

class BookInsert(DetailView):
    template_name = 'insert.html'
    model = BookInfo

InfoBookproject/InfoBookapp/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>蔵書検索</title>
  </head>
  <body>
    <h1>蔵書管理</h1>
    {% block header %}
    {% endblock header %}

    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

InfoBookproject/InfoBookapp/templates/create.html
{% extends 'base.html' %}

{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<h1>create</h1>
{% endblock content %}

InfoBookproject/InfoBookapp/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<div class="container">
    <div class="row row-cols-1">
        <a href="{% url 'InfoBookapp:list' %}">蔵書データの表示</a>
        <a href="{% url 'InfoBookapp:create' %}">蔵書データの登録</a>
        <a href="{% url 'InfoBookapp:insert' %}">蔵書データの検索</a>
      <div class="col">蔵書データの修正(表示・検索してから)</div>
      <div class="col">蔵書データの削除(表示・検索してから)</div>
    </div>
  </div>
{% endblock content %}

InfoBookproject/InfoBookapp/templates/insert.html
{% extends 'base.html' %}

{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<h1>insert</h1>
{% endblock content %}

InfoBookproject/InfoBookapp/templates/list.html
{% extends 'base.html' %}

{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<div class="container">
  {% for item in object_item %}
    <ul>
      <li>{{ item.title }}</li>
    </ul>
  {% endfor %}
</div>
{% endblock content %}